BANCO_TEMAS = {
    "Alimentação": [
        {'pergunta': 'Qual o ingrediente que faz o pão crescer?', 'opcoes': ['Fermento', 'Sal', 'Açúcar', 'Ovo'], 'correta': 'Fermento', 'tipo': 'normal'},
        {'pergunta': 'De qual planta é extraído o azeite?', 'opcoes': ['Oliva', 'Girassol', 'Milho', 'Soja'], 'correta': 'Oliva', 'tipo': 'normal'},
        {'pergunta': 'Qual o nome do prato japonês de peixe cru?', 'opcoes': ['Sashimi', 'Temaki', 'Uramaki', 'Yakissoba'], 'correta': 'Sashimi', 'tipo': 'normal'},
        {'pergunta': 'Qual fruta é a base do vinho?', 'opcoes': ['Uva', 'Maçã', 'Pera', 'Cereja'], 'correta': 'Uva', 'tipo': 'normal'},
        {'pergunta': 'Qual é o principal ingrediente do Hummus?', 'opcoes': ['Grão-de-bico', 'Lentilha', 'Feijão', 'Ervilha'], 'correta': 'Grão-de-bico', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato italiano feito com arroz e açafrão?', 'opcoes': ['Risoto', 'Lasagna', 'Gnocchi', 'Polenta'], 'correta': 'Risoto', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do pão tradicional francês?', 'opcoes': ['Baguete', 'Croissant', 'Focaccia', 'Ciabatta'], 'correta': 'Baguete', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato indiano feito com carne e especiarias, servido com arroz?', 'opcoes': ['Curry', 'Tandoori', 'Biryani', 'Masala'], 'correta': 'Biryani', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do queijo italiano que tem buracos?', 'opcoes': ['Parmesão', 'Mozzarella', 'Gorgonzola', 'Emmental'], 'correta': 'Emmental', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato mexicano feito com tortilhas recheadas e cobertas com molho?', 'opcoes': ['Taco', 'Enchilada', 'Quesadilla', 'Burrito'], 'correta': 'Enchilada', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato brasileiro feito com feijão preto, carne de porco e arroz?', 'opcoes': ['Feijoada', 'Moqueca', 'Vatapá', 'Bobó'], 'correta': 'Feijoada', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato francês feito com carne cozida lentamente em vinho tinto?', 'opcoes': ['Coq au Vin', 'Boeuf Bourguignon', 'Ratatouille', 'Bouillabaisse'], 'correta': 'Boeuf Bourguignon', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato espanhol feito com arroz, frutos do mar e açafrão?', 'opcoes': ['Paella', 'Gazpacho', 'Tortilla', 'Tapas'], 'correta': 'Paella', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato italiano feito com massa, molho de tomate e queijo?', 'opcoes': ['Pizza', 'Lasagna', 'Spaghetti', 'Fettuccine'], 'correta': 'Pizza', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato japonês feito com arroz, peixe cru e algas?', 'opcoes': ['Sushi', 'Sashimi', 'Temaki', 'Uramaki'], 'correta': 'Sushi', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato indiano feito com pão achatado e recheado?', 'opcoes': ['Naan', 'Roti', 'Paratha', 'Chapati'], 'correta': 'Paratha', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato brasileiro feito com carne seca, mandioca e queijo coalho?', 'opcoes': ['Escondidinho', 'Baião de Dois', 'Carne de Sol com Mandioca', 'Mandioca Recheada'], 'correta': 'Escondidinho', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato francês feito com carne de coelho, vinho tinto e cogumelos?', 'opcoes': ['Coq au Vin', 'Lapin à la Moutarde', 'Boeuf Bourguignon', 'Ratatouille'], 'correta': 'Lapin à la Moutarde', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato espanhol feito com ovos, batatas e cebolas?', 'opcoes': ['Tortilla', 'Gazpacho', 'Paella', 'Tapas'], 'correta': 'Tortilla', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do prato italiano feito com massa recheada e coberta com molho?', 'opcoes': ['Ravioli', 'Tortellini', 'Gnocchi', 'Fettuccine'], 'correta': 'Ravioli', 'tipo': 'normal'},
    ],
    "Geografia": [
        {'pergunta': 'Qual o maior oceano do mundo?', 'opcoes': ['Atlântico', 'Índico', 'Ártico', 'Pacífico'], 'correta': 'Pacífico', 'tipo': 'normal'},
        {'pergunta': 'Em qual continente fica o Egito?', 'opcoes': ['Ásia', 'África', 'Europa', 'América'], 'correta': 'África', 'tipo': 'normal'},
        {'pergunta': 'Qual a capital da Argentina?', 'opcoes': ['Santiago', 'Montevidéu', 'Buenos Aires', 'Lima'], 'correta': 'Buenos Aires', 'tipo': 'normal'},
        {'pergunta': 'Qual o rio mais extenso do mundo?', 'opcoes': ['Nilo', 'Amazonas', 'Mississipi', 'Ganges'], 'correta': 'Amazonas', 'tipo': 'normal'},
        {'pergunta': 'Qual país é conhecido como "Terra do Sol Nascente"?', 'opcoes': ['China', 'Japão', 'Coreia do Sul', 'Tailândia'], 'correta': 'Japão', 'tipo': 'normal'},
        {'pergunta': 'Qual é a montanha mais alta do mundo?', 'opcoes': ['K2', 'Everest', 'Kangchenjunga', 'Lhotse'], 'correta': 'Everest', 'tipo': 'normal'},
        {'pergunta': 'Qual é o país com a maior população do mundo?', 'opcoes': ['Índia', 'Estados Unidos', 'Indonésia', 'China'], 'correta': 'China', 'tipo': 'normal'},
        {'pergunta': 'Qual é a capital da Austrália?', 'opcoes': ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], 'correta': 'Canberra', 'tipo': 'normal'},
        {'pergunta': 'Qual é o deserto mais extenso do mundo?', 'opcoes': ['Sahara', 'Gobi', 'Kalahari', 'Antártico'], 'correta': 'Antártico', 'tipo': 'normal'},
        {'pergunta': 'Qual é o país com mais ilhas no mundo?', 'opcoes': ['Indonésia', 'Finlândia', 'Canadá', 'Noruega'], 'correta': 'Finlândia', 'tipo': 'normal'},
        {'pergunta': 'Qual é a capital do Canadá?', 'opcoes': ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], 'correta': 'Ottawa', 'tipo': 'normal'},
        {'pergunta': 'Qual é o país mais extenso do mundo?', 'opcoes': ['Canadá', 'China', 'Estados Unidos', 'Rússia'], 'correta': 'Rússia', 'tipo': 'normal'},
        {'pergunta': 'Qual é a capital da França?', 'opcoes': ['Lyon', 'Marselha', 'Paris', 'Toulouse'], 'correta': 'Paris', 'tipo': 'normal'},
        {'pergunta': 'Qual é o país com mais vulcões ativos?', 'opcoes': ['Indonésia', 'Japão', 'Estados Unidos', 'Itália'], 'correta': 'Indonésia', 'tipo': 'normal'},
        {'pergunta': 'Qual é a capital da Rússia?', 'opcoes': ['São Petersburgo', 'Moscou', 'Novosibirsk', 'Yekaterinburg'], 'correta': 'Moscou', 'tipo': 'normal'},
        {'pergunta': 'Qual é o país mais populoso da África?', 'opcoes': ['Nigéria', 'Egito', 'África do Sul', 'Etiópia'], 'correta': 'Nigéria', 'tipo': 'normal'},
        {'pergunta': 'Qual é a capital da Índia?', 'opcoes': ['Mumbai', 'Nova Délhi', 'Bangalore', 'Hyderabad'], 'correta': 'Nova Délhi', 'tipo': 'normal'},
        {'pergunta': 'Qual é o país com mais línguas faladas?', 'opcoes': ['Papua Nova Guiné', 'Índia', 'Indonésia', 'Nigéria'], 'correta': 'Papua Nova Guiné', 'tipo': 'normal'},
        {'pergunta': 'Qual é a capital da Alemanha?', 'opcoes': ['Munique', 'Frankfurt', 'Berlim', 'Hamburgo'], 'correta': 'Berlim', 'tipo': 'normal'},
        {'pergunta': 'Qual é o país mais rico do mundo em PIB per capita?', 'opcoes': ['Luxemburgo', 'Suíça', 'Noruega', 'Irlanda'], 'correta': 'Luxemburgo', 'tipo': 'normal'},
    ],
    "Tecnologia": [
        {'pergunta': 'O que significa a sigla CPU?', 'opcoes': ['Central Process Unit', 'Core Power Use', 'Control Program Unit', 'Central Power Unit'], 'correta': 'Central Process Unit', 'tipo': 'normal'},
        {'pergunta': 'Qual linguagem é famosa pelo símbolo da cobra?', 'opcoes': ['Java', 'C++', 'Python', 'Ruby'], 'correta': 'Python', 'tipo': 'normal'},
        {'pergunta': 'Quem fundou a Microsoft?', 'opcoes': ['Steve Jobs', 'Mark Zuckerberg', 'Bill Gates', 'Elon Musk'], 'correta': 'Bill Gates', 'tipo': 'normal'},
        {'pergunta': 'Qual o comando SQL usado para buscar dados?', 'opcoes': ['GET', 'SELECT', 'FIND', 'SEARCH'], 'correta': 'SELECT', 'tipo': 'normal'},
        {'pergunta': 'Qual empresa criou o sistema operacional Android?', 'opcoes': ['Apple', 'Google', 'Microsoft', 'Samsung'], 'correta': 'Google', 'tipo': 'normal'},
        {'pergunta': 'O que é um "bug" em programação?', 'opcoes': ['Um erro de código', 'Um tipo de software', 'Um dispositivo de hardware', 'Um framework'], 'correta': 'Um erro de código', 'tipo': 'normal'},
        {'pergunta': 'Qual é a função principal de um firewall?', 'opcoes': ['Acelerar a internet', 'Proteger contra ataques cibernéticos', 'Gerenciar arquivos', 'Melhorar o desempenho'], 'correta': 'Proteger contra ataques cibernéticos', 'tipo': 'normal'},
        {'pergunta': 'O que é "cloud computing"?', 'opcoes': ['Computação em nuvem', 'Computação local', 'Computação pessoal', 'Computação móvel'], 'correta': 'Computação em nuvem', 'tipo': 'normal'},
        {'pergunta': 'Qual é o famoso sistema de código aberto para servidores?', 'opcoes': ['Windows Server', 'Linux', 'macOS Server', 'Unix'], 'correta': 'Linux', 'tipo': 'normal'},
        {'pergunta': 'O que é "phishing"?', 'opcoes': ['Um tipo de malware', 'Uma técnica de engenharia social para roubo de dados', 'Um protocolo de segurança', 'Um antivírus'], 'correta': 'Uma técnica de engenharia social para roubo de dados', 'tipo': 'normal'},
        {'pergunta': 'Qual é a empresa por trás do processador "M1"?', 'opcoes': ['Intel', 'AMD', 'Apple', 'NVIDIA'], 'correta': 'Apple', 'tipo': 'normal'},
        {'pergunta': 'O que é "IoT"?', 'opcoes': ['Internet of Things', 'Input Output Technology', 'Internal Operating System', 'Intelligent Online Tools'], 'correta': 'Internet of Things', 'tipo': 'normal'},
        {'pergunta': 'Qual é a linguagem de programação mais usada para desenvolvimento web?', 'opcoes': ['JavaScript', 'Python', 'Ruby', 'PHP'], 'correta': 'JavaScript', 'tipo': 'normal'},
        {'pergunta': 'O que é "machine learning"?', 'opcoes': ['Aprendizado de máquina', 'Aprendizado humano', 'Aprendizado de software', 'Aprendizado de dados'], 'correta': 'Aprendizado de máquina', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do famoso assistente virtual da Amazon?', 'opcoes': ['Siri', 'Alexa', 'Google Assistant', 'Cortana'], 'correta': 'Alexa', 'tipo': 'normal'},
        {'pergunta': 'O que é "blockchain"?', 'opcoes': ['Uma cadeia de blocos de dados', 'Um tipo de criptomoeda', 'Um protocolo de segurança', 'Um sistema de armazenamento em nuvem'], 'correta': 'Uma cadeia de blocos de dados', 'tipo': 'normal'},
        {'pergunta': 'Qual é a empresa por trás do sistema operacional "iOS"?', 'opcoes': ['Google', 'Microsoft', 'Apple', 'Samsung'], 'correta': 'Apple', 'tipo': 'normal'},
        {'pergunta': 'O que é "open source"?', 'opcoes': ['Software de código aberto', 'Software proprietário', 'Software gratuito', 'Software de código fechado'], 'correta': 'Software de código aberto', 'tipo': 'normal'},
        {'pergunta': 'Qual é a linguagem de programação mais usada para ciência de dados?', 'opcoes': ['R', 'Python', 'SAS', 'Julia'], 'correta': 'Python', 'tipo': 'normal'},
        {'pergunta': 'O que é "cybersecurity"?', 'opcoes': ['Segurança cibernética', 'Segurança física', 'Segurança de dados', 'Segurança de rede'], 'correta': 'Segurança cibernética', 'tipo': 'normal'},
    ],
    "Ciência": [
        {'pergunta': 'Qual o centro do nosso sistema solar?', 'opcoes': ['Terra', 'Marte', 'Sol', 'Lua'], 'correta': 'Sol', 'tipo': 'normal'},
        {'pergunta': 'Qual o metal cujo símbolo químico é Au?', 'opcoes': ['Prata', 'Cobre', 'Ouro', 'Ferro'], 'correta': 'Ouro', 'tipo': 'normal'},
        {'pergunta': 'Quantos ossos tem o corpo humano adulto?', 'opcoes': ['206', '150', '300', '250'], 'correta': '206', 'tipo': 'normal'},
        {'pergunta': 'Qual a fórmula química da água?', 'opcoes': ['H2O', 'CO2', 'O2', 'NaCl'], 'correta': 'H2O', 'tipo': 'normal'},
        {'pergunta': 'Quem é conhecido como o pai da teoria da evolução?', 'opcoes': ['Isaac Newton', 'Albert Einstein', 'Charles Darwin', 'Galileu Galilei'], 'correta': 'Charles Darwin', 'tipo': 'normal'},
        {'pergunta': 'Qual é a unidade de medida da força?', 'opcoes': ['Newton', 'Joule', 'Watt', 'Pascal'], 'correta': 'Newton', 'tipo': 'normal'},
        {'pergunta': 'Qual é o maior planeta do nosso sistema solar?', 'opcoes': ['Saturno', 'Júpiter', 'Urano', 'Netuno'], 'correta': 'Júpiter', 'tipo': 'normal'},
        {'pergunta': 'Qual é o planeta mais próximo do Sol?', 'opcoes': ['Vênus', 'Marte', 'Mercúrio', 'Júpiter'], 'correta': 'Mercúrio', 'tipo': 'normal'},
        {'pergunta': 'Como as plantas produzem seu alimento?', 'opcoes': ['Respiração', 'Fotossíntese', 'Transpiração', 'Germinação'], 'correta': 'Fotossíntese', 'tipo': 'normal'},
        {'pergunta': 'Qual físico desenvolveu a teoria da relatividade?', 'opcoes': ['Isaac Newton', 'Albert Einstein', 'Nikola Tesla', 'Galileu Galilei'], 'correta': 'Albert Einstein', 'tipo': 'normal'},
        {'pergunta': 'Qual é o processo de divisão celular que resulta em células filhas idênticas?', 'opcoes': ['Meiose', 'Mitose', 'Fissão Binária', 'Budding'], 'correta': 'Mitose', 'tipo': 'normal'},
        {'pergunta': 'Qual é a camada mais externa da Terra?', 'opcoes': ['Manto', 'Núcleo', 'Crosta', 'Litosfera'], 'correta': 'Crosta', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do processo pelo qual as plantas perdem água para a atmosfera?', 'opcoes': ['Transpiração', 'Respiração', 'Fotossíntese', 'Germinação'], 'correta': 'Transpiração', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do processo pelo qual as células se especializam em diferentes tipos?', 'opcoes': ['Diferenciação', 'Mitose', 'Meiose', 'Fissão Binária'], 'correta': 'Diferenciação', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do processo pelo qual as plantas absorvem água do solo?', 'opcoes': ['Transpiração', 'Absorção', 'Fotossíntese', 'Germinação'], 'correta': 'Absorção', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do processo pelo qual as plantas produzem sementes?', 'opcoes': ['Germinação', 'Polinização', 'Fertilização', 'Frutificação'], 'correta': 'Polinização', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do processo pelo qual as plantas crescem em direção à luz?', 'opcoes': ['Fototropismo', 'Gravitropismo', 'Hidrotropismo', 'Quimiotropismo'], 'correta': 'Fototropismo', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do processo pelo qual as plantas perdem suas folhas no outono?', 'opcoes': ['Decídua', 'Perene', 'Caducifólia', 'Evergreen'], 'correta': 'Caducifólia', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do processo pelo qual as plantas produzem flores?', 'opcoes': ['Germinação', 'Polinização', 'Fertilização', 'Floração'], 'correta': 'Floração', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do processo pelo qual as plantas produzem frutos?', 'opcoes': ['Germinação', 'Polinização', 'Fertilização', 'Frutificação'], 'correta': 'Frutificação', 'tipo': 'normal'},
    ],
    "Esportes": [
        {'pergunta': 'Quantos jogadores tem um time de futebol em campo?', 'opcoes': ['10', '11', '12', '9'], 'correta': '11', 'tipo': 'normal'},
        {'pergunta': 'Qual país ganhou mais Copas do Mundo?', 'opcoes': ['Alemanha', 'Itália', 'Brasil', 'Argentina'], 'correta': 'Brasil', 'tipo': 'normal'},
        {'pergunta': 'Qual esporte usa a expressão "Home Run"?', 'opcoes': ['Basquete', 'Beisebol', 'Tênis', 'Golfe'], 'correta': 'Beisebol', 'tipo': 'normal'},
        {'pergunta': 'Em qual esporte se usa um "puck"?', 'opcoes': ['Hóquei no Gelo', 'Futebol', 'Basquete', 'Rugby'], 'correta': 'Hóquei no Gelo', 'tipo': 'normal'},
        {'pergunta': 'Qual é o torneio de tênis mais famoso do mundo?', 'opcoes': ['Wimbledon', 'Roland Garros', 'US Open', 'Australian Open'], 'correta': 'Wimbledon', 'tipo': 'normal'},
        {'pergunta': 'Qual país sediou os Jogos Olímpicos de 2016?', 'opcoes': ['China', 'Reino Unido', 'Brasil', 'Rússia'], 'correta': 'Brasil', 'tipo': 'normal'},
        {'pergunta': 'Qual jogador de basquete é conhecido como "Air"?', 'opcoes': ['Michael Jordan', 'LeBron James', 'Kobe Bryant', 'Magic Johnson'], 'correta': 'Michael Jordan', 'tipo': 'normal'},
        {'pergunta': 'Onde fica o estádio La Bombonera?', 'opcoes': ['Rio de Janeiro', 'São Paulo', 'Buenos Aires', 'Montevidéu'], 'correta': 'Buenos Aires', 'tipo': 'normal'},
        {'pergunta': 'Qual tenista suíço ganhou 20 Grand Slams?', 'opcoes': ['Rafael Nadal', 'Novak Djokovic', 'Roger Federer', 'Andy Murray'], 'correta': 'Roger Federer', 'tipo': 'normal'},
        {'pergunta': 'Qual jogador argentino é chamado de "La Pulga"?', 'opcoes': ['Diego Maradona', 'Lionel Messi', 'Sergio Agüero', 'Carlos Tevez'], 'correta': 'Lionel Messi', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Real Madrid?', 'opcoes': ['Camp Nou', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Santiago Bernabéu', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Barcelona?', 'opcoes': ['Camp Nou', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Camp Nou', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Manchester United?', 'opcoes': ['Camp Nou', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Old Trafford', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Bayern de Munique?', 'opcoes': ['Camp Nou', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Allianz Arena', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Paris Saint-Germain?', 'opcoes': ['Parc des Princes', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Parc des Princes', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Juventus?', 'opcoes': ['Allianz Stadium', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Allianz Stadium', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Liverpool?', 'opcoes': ['Anfield', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Anfield', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Chelsea?', 'opcoes': ['Stamford Bridge', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Stamford Bridge', 'tipo': 'normal'},
        {'pergunta': 'Qual é o nome do estádio do Manchester City?', 'opcoes': ['Etihad Stadium', 'Santiago Bernabéu', 'Allianz Arena', 'Old Trafford'], 'correta': 'Etihad Stadium', 'tipo': 'normal'},
    ],
    "Gênio Quiz": [
        {"pergunta": "Se ontem fosse amanhã, hoje seria sexta. Que dia é hoje?", "opcoes": ["Quarta", "Quinta", "Sexta", "Domingo"], "correta": "Domingo", "tipo": "normal"},
        {"pergunta": "Aperte o botão premiado!", "opcoes": ["Errado", "Não é esse", "Quase lá", "AQUI!"], "correta": "AQUI!", "tipo": "botao_fujao"},
        {"pergunta": "Qual a cor do cavalo BRANCO de Napoleão?", "opcoes": ["Preto", "Cinza", "Marrom", "Azul"], "correta": "Branco", "tipo": "texto_pergunta"},
        {"pergunta": "O que é mais pesado: 1 kg de chumbo ou 1 kg de penas?", "opcoes": ["Chumbo", "Penas", "Pesam o mesmo", "Depende do tamanho"], "correta": "Pesam o mesmo", "tipo": "texto_pergunta"},
        {"pergunta": "Se um avião cai na fronteira entre Brasil e Argentina, onde enterram os sobreviventes?", "opcoes": ["Brasil", "Argentina", "Nenhum dos dois", "No meio da fronteira"], "correta": "Nenhum dos dois", "tipo": "texto_pergunta"},
        {"pergunta": "Qual é o próximo número na sequência: 2, 3, 5, 7, 11, ?", "opcoes": ["13", "14", "15", "17"], "correta": "13", "tipo": "normal"},
        {"pergunta": "O que é mais rápido: a luz ou o som?", "opcoes": ["Luz", "Som", "Ambos são iguais", "Depende do meio"], "correta": "Luz", "tipo": "normal"},
        {"pergunta": "Para onde vai a fumaça de um trem elétrico?", "opcoes": ["Norte", "Sul", "Fumaça não existe", "Depende do vento"], "correta": "Fumaça não existe", "tipo": "texto_pergunta"},
        {"pergunta": "Qual é mais importante para um peixe: água ou ar?", "opcoes": ["Água", "Ar", "Ambos são iguais", "Depende do peixe"], "correta": "Água", "tipo": "normal"},
        {"pergunta": "Quantos meses têm 28 dias?", "opcoes": ["1", "2", "6", "12"], "correta": "12", "tipo": "texto_pergunta"},
        {"pergunta": "O que é mais leve: 1 kg de algodão ou 1 kg de chumbo?", "opcoes": ["Algodão", "Chumbo", "Pesam o mesmo", "Depende do volume"], "correta": "Pesam o mesmo", "tipo": "texto_pergunta"},
        {"pergunta": "Se um avião cai no mar, onde enterram os sobreviventes?", "opcoes": ["Na praia", "No fundo do mar", "Nenhum dos dois", "Em terra firme"], "correta": "Nenhum dos dois", "tipo": "texto_pergunta"},
        {"pergunta": "Qual é o próximo número na sequência: 1, 4, 9, 16, ?", "opcoes": ["20", "25", "30", "36"], "correta": "25", "tipo": "normal"},
        {"pergunta": "O que é mais quente: fogo ou gelo?", "opcoes": ["Fogo", "Gelo", "Ambos são iguais", "Depende do contexto"], "correta": "Fogo", "tipo": "normal"},
        {'pergunta': 'Se um avião cai na fronteira entre Brasil e Argentina, onde enterram os sobreviventes?', 'opcoes': ['Brasil', 'Argentina', 'Nenhum dos dois', 'No meio da fronteira'], 'correta': 'Nenhum dos dois', 'tipo': 'texto_pergunta'},
        {'pergunta': 'Qual é o próximo número na sequência: 2, 3, 5, 7, 11, ?', 'opcoes': ['13', '14', '15', '17'], 'correta': '13', 'tipo': 'normal'},
        {'pergunta': 'O que é mais rápido: a luz ou o som?', 'opcoes': ['Luz', 'Som', 'Ambos são iguais', 'Depende do meio'], 'correta': 'Luz', 'tipo': 'normal'},
        {'pergunta': 'Para onde vai a fumaça de um trem elétrico?', 'opcoes': ['Norte', 'Sul', 'Fumaça não existe', 'Depende do vento'], 'correta': 'Fumaça não existe', 'tipo': 'texto_pergunta'},
        {'pergunta': 'Qual é mais importante para um peixe: água ou ar?', 'opcoes': ['Água', 'Ar', 'Ambos são iguais', 'Depende do peixe'], 'correta': 'Água', 'tipo': 'normal'},
    ],
    "Matemática": [
        {'pergunta': 'Quanto é 7 × 8?', 'opcoes': ['54', '56', '64', '48'], 'correta': '56', 'tipo': 'normal'},
        {'pergunta': 'Qual é a raiz quadrada de 81?', 'opcoes': ['7', '8', '9', '10'], 'correta': '9', 'tipo': 'normal'},
        {'pergunta': 'Quanto é 15% de 200?', 'opcoes': ['20', '25', '30', '35'], 'correta': '30', 'tipo': 'normal'},
        {'pergunta': 'Qual o próximo número: 2, 4, 8, 16, ?', 'opcoes': ['18', '20', '32', '64'], 'correta': '32', 'tipo': 'normal'},
        {'pergunta': 'Quanto é 12 dividido por 0?', 'opcoes': ['0', 'Infinito', 'Indefinido', '12'], 'correta': 'Indefinido', 'tipo': 'normal'},
        {'pergunta': 'Qual é o valor de π arredondado para duas casas decimais?', 'opcoes': ['3.12', '3.14', '3.16', '3.18'], 'correta': '3.14', 'tipo': 'normal'},
        {'pergunta': 'Quanto é 5 elevado a 3?', 'opcoes': ['15', '25', '125', '625'], 'correta': '125', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula para calcular a área de um círculo?', 'opcoes': ['A = πr²', 'A = 2πr', 'A = πd²/4', 'A = r²'], 'correta': 'A = πr²', 'tipo': 'normal'},
        {'pergunta': 'Quanto é log₁₀(100)?', 'opcoes': ['1', '2', '10', '-1'], 'correta': '2', 'tipo': 'normal'},
        {'pergunta': 'Se x + y = 10 e x - y = 4, qual é o valor de x?', 'opcoes': ['2', '4', '7', '8'], 'correta': '7', 'tipo': 'normal'},
        {'pergunta': 'Quanto é 0 dividido por 5?', 'opcoes': ['0', 'Infinito', 'Indefinido', '5'], 'correta': '0', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula para calcular a hipotenusa de um triângulo retângulo?', 'opcoes': ['a² + b² = c²', 'a² - b² = c²', 'a² × b² = c²', 'a² ÷ b² = c²'], 'correta': 'a² + b² = c²', 'tipo': 'normal'},
        {'pergunta': 'Quanto é 10% de 50?', 'opcoes': ['5', '10', '15', '20'], 'correta': '5', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula para calcular o volume de um cubo?', 'opcoes': ['V = a³', 'V = 6a²', 'V = a⁴', 'V = 3a³'], 'correta': 'V = a³', 'tipo': 'normal'},
        {'pergunta': 'Quanto é 2 elevado a 5?', 'opcoes': ['16', '32', '64', '128'], 'correta': '32', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula para calcular a média aritmética?', 'opcoes': ['M = (x₁ + x₂ + ... + xₙ) / n', 'M = (x₁ × x₂ × ... × xₙ)^(1/n)', 'M = (x₁ + x₂ + ... + xₙ) / (n - 1)', 'M = (x₁ - x₂ - ... - xₙ) / n'], 'correta': 'M = (x₁ + x₂ + ... + xₙ) / n', 'tipo': 'normal'},
        {'pergunta': 'Quanto é 15 dividido por 3?', 'opcoes': ['3', '4', '5', '6'], 'correta': '5', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula para calcular a área de um triângulo?', 'opcoes': ['A = (base × altura) / 2', 'A = base × altura', 'A = (base + altura) / 2', 'A = base² + altura²'], 'correta': 'A = (base × altura) / 2', 'tipo': 'normal'},
        {'pergunta': 'Quanto é 9 elevado a 2?', 'opcoes': ['18', '27', '81', '729'], 'correta': '81', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula para calcular o perímetro de um retângulo?', 'opcoes': ['P = 2(l + w)', 'P = l × w', 'P = l + w', 'P = 4l'], 'correta': 'P = 2(l + w)', 'tipo': 'normal'},
    ],
    "Física": [
        {'pergunta': 'Qual é a unidade de medida da força?', 'opcoes': ['Newton', 'Joule', 'Watt', 'Pascal'], 'correta': 'Newton', 'tipo': 'normal'},
        {'pergunta': 'Qual é a velocidade da luz no vácuo?', 'opcoes': ['300.000 km/s', '150.000 km/s', '299.792 km/s', '250.000 km/s'], 'correta': '299.792 km/s', 'tipo': 'normal'},
        {'pergunta': 'Quem formulou as leis do movimento?', 'opcoes': ['Albert Einstein', 'Isaac Newton', 'Galileu Galilei', 'Nikola Tesla'], 'correta': 'Isaac Newton', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula da energia cinética?', 'opcoes': ['E = mc²', 'E = ½mv²', 'E = mgh', 'E = Fd'], 'correta': 'E = ½mv²', 'tipo': 'normal'},
        {'pergunta': 'O que é a gravidade?', 'opcoes': ['Uma força que atrai objetos com massa', 'Uma forma de energia', 'Um tipo de radiação', 'Um campo magnético'], 'correta': 'Uma força que atrai objetos com massa', 'tipo': 'normal'},
        {'pergunta': 'Qual é a terceira lei de Newton?', 'opcoes': ['Para cada ação, há uma reação igual e oposta', 'A força é igual à massa vezes a aceleração', 'Um objeto em repouso permanece em repouso', 'A energia não pode ser criada nem destruída'], 'correta': 'Para cada ação, há uma reação igual e oposta', 'tipo': 'normal'},
        {'pergunta': 'O que é a entropia?', 'opcoes': ['Uma medida da desordem em um sistema', 'A energia total de um sistema', 'A força de atração entre partículas', 'A velocidade de uma reação química'], 'correta': 'Uma medida da desordem em um sistema', 'tipo': 'normal'},
        {'pergunta': 'Qual físico desenvolveu a teoria da relatividade?', 'opcoes': ['Isaac Newton', 'Albert Einstein', 'Nikola Tesla', 'Galileu Galilei'], 'correta': 'Albert Einstein', 'tipo': 'normal'},
        {'pergunta': 'O que é a dualidade onda-partícula?', 'opcoes': ['Partículas subatômicas podem se comportar como ondas e vice-versa', 'A luz é composta por fótons', 'A matéria é feita de ondas de energia', 'Partículas existem em dois lugares ao mesmo tempo'], 'correta': 'Partículas subatômicas podem se comportar como ondas e vice-versa', 'tipo': 'normal'},
        {'pergunta': 'Qual é a unidade de medida da energia?', 'opcoes': ['Newton', 'Joule', 'Watt', 'Pascal'], 'correta': 'Joule', 'tipo': 'normal'},
        {'pergunta': 'O que é a superposição quântica?', 'opcoes': ['Partículas podem estar em múltiplos estados ao mesmo tempo', 'A energia de um sistema é quantizada', 'Partículas subatômicas têm massa zero', 'A luz é composta por ondas'], 'correta': 'Partículas podem estar em múltiplos estados ao mesmo tempo', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula da lei de Ohm?', 'opcoes': ['V = IR', 'P = IV', 'E = mc²', 'F = ma'], 'correta': 'V = IR', 'tipo': 'normal'},
        {'pergunta': 'O que é a inércia?', 'opcoes': ['A tendência de um objeto em resistir a mudanças em seu estado de movimento', 'A força que mantém os planetas em órbita', 'A energia armazenada em um sistema', 'A velocidade de um objeto'], 'correta': 'A tendência de um objeto em resistir a mudanças em seu estado de movimento', 'tipo': 'normal'},
        {'pergunta': 'Qual é a unidade de medida da pressão?', 'opcoes': ['Newton', 'Joule', 'Watt', 'Pascal'], 'correta': 'Pascal', 'tipo': 'normal'},
        {'pergunta': 'O que é a radiação?', 'opcoes': ['Emissão de energia na forma de ondas ou partículas', 'A força que atrai objetos com massa', 'A energia total de um sistema', 'A velocidade de uma reação química'], 'correta': 'Emissão de energia na forma de ondas ou partículas', 'tipo': 'normal'},
        {'pergunta': 'Qual é a fórmula da segunda lei de Newton?', 'opcoes': ['F = ma', 'E = mc²', 'V = IR', 'P = IV'], 'correta': 'F = ma', 'tipo': 'normal'},
        {'pergunta': 'O que é a relatividade geral?', 'opcoes': ['Teoria que descreve a gravidade como a curvatura do espaço-tempo', 'Teoria que descreve a gravidade como uma força de atração entre massas', 'Teoria que descreve a gravidade como uma forma de energia', 'Teoria que descreve a gravidade como um campo magnético'], 'correta': 'Teoria que descreve a gravidade como a curvatura do espaço-tempo', 'tipo': 'normal'},
    ],
}